### ISSUE TITLE
Convert docstring examples to jldoctests.

### ISSUE THREAD

**Issue by kdpsingh** [kdpsingh/Tidier.jl#19]
I would like to convert all of the current documentation string examples into jldoctests. This seems to be a really efficient way to incorporate testing into the package while also making the documentation better (a win-win!).

I would love to get help with this.

Please reply to this issue if interested to work on this, and I will "assign" it to you to prevent redundant work.

**Comment by zzhaozheUM** [comment]
I can handle this.

**Comment by rdboyes** [comment]
I wouldn't remove it entirely personally - see here: https://documenter.juliadocs.org/stable/man/doctests/index.html#Doctesting-as-Part-of-Testing - the current runtests.jl file can be replaced with a call to doctests(Tidier). This would make it easy to automate the running of the doctests and also allow future unit tests that don't belong in the documentation to be added

**Comment by kdpsingh** [comment]
Thank you @rdboyes. Would you be willing to review the PR when it is ready for merging?

If not, all good! Just wanted to ask.

**Comment by kdpsingh** [comment]
Resolved by PR #25.
