### ISSUE TITLE
Logo refresh idea?

### ISSUE THREAD

**Issue by pdimens** [kdpsingh/Tidier.jl#56]
Hello! I'm a big fan and supporter of Tidier.jl and the goal to ease R users' transition into Julia for data manipulation. I'm a Julia package dev too (PopGen.jl, PopGenCore.jl, PopGenSims.jl) :smile:. 

I recognized that the Tidier.jl logo was hexagonal, _a la_ the R styling, so I was curious to see how similar to the `tidyr` logo it was, considering that is where the package draws inspiration. I suppose I had never seen the tidyr logo before because it's not what I expected, but as a fun little challenge to procrastinate actual work, I drafted up a logo (I do that sometimes, it's a weird hobby) that combines elements of both tidyr and tidier logos. In the screenshot below are (1) tidyr, (2) tidier, and (3) my drafted hybrid.
![image](https://user-images.githubusercontent.com/19176506/225654244-db9db7ea-6a55-46be-be46-1ccba90516ec.png)
It's not very much work to make these or edit them. If you were interested in pursuing something along these lines, we can chat about it in better detail. If not, all good(!) and feel free to close this ticket. I'm also available in the Julia Slack (pdimens)

**Comment by kdpsingh** [comment]
Hi @pdimens, thank you so much for bringing your creativity to Tidier.jl!

I love the work you've done with other Julia packages, and I'm definitely open to ideas, suggestions, and contributions from others on Tidier.

I'll supply of a bit of additional context and would love to get your thoughts.

Although the name `Tidier` is most similar to the `tidyr` package, the `tidyr` package is one of many packages that make up the larger R `tidyverse` ecosystem, and `Tidier` is actually meant to apply to the larger `tidyverse` ecosystem rather than the `tidyr` package specifically. See here for a list of core `tidyverse` packages: https://www.tidyverse.org.

With Tidier, we've started by writing wrappers for `dplyr` and `tidyr` but we *may* expand to cover *some* of the others (e.g., `readr`, `forcats`, and `ggplot2`). That's partly why I kept the logo a bit different rather than trying to match it to `tidyr` specifically.

With that additional context, what do you think?

**Comment by pdimens** [comment]
Gotcha! Well, I have an idea that I could try this afternoon.

**Comment by pdimens** [comment]
Here's some drafts of what we discussed in Slack 
![image](https://user-images.githubusercontent.com/19176506/225718306-64813e27-b5a5-40c1-9f8d-530a9d8f2a0e.png)

**Comment by kdpsingh** [comment]
I'm a HUGE fan of the second option!! I like option 1 too but I like the larger font size in the second option that makes it a bit more readable.

Can we make the sides of the hex straight and not rounded? If we can do that I think this is pretty much final.

Let me know if that sounds okay to you. @rdboyes @zzhaozheUM  @lazarusA @camilogarciabotero @pitmonticone feel free to chime I with thoughts.

**Comment by kdpsingh** [comment]
The world is not ready for options 3 and 4. 😂

**Comment by lazarusA** [comment]
I'm not familiar with those elements in the logo. What does tidier does? clean and cut? In my mind is more like a packing, re-packing stuff and combining and creating new elements. I get the point about being similar to R, but I wonder if now is better to start diverging a little bit a give it a different spin.

**Comment by kdpsingh** [comment]
Thanks @lazarusA. It's a plier (to manipulate and reshape data) and a broom (to clean data).

I like the visual elements and do want to keep it visually linked to the original tidyverse, with a bit of Julia flavor (which I feel like the dots convey nicely).

**Comment by camilogarciabotero** [comment]
Wow, those are quite nice logos! I like the julian adaptation to the font too much. Regarding the sides, I think that maybe rounding them is a differential point in contrast to those from R. Then, 2 and 4 are the ones I like the most.

**Comment by zzhaozheUM** [comment]
All designs are astonishing! I also prefer option 1 but a larger font could make this better. Option 4 is wild but it's my secrete love.

**Comment by pdimens** [comment]
@kdpsingh everything is in vector format on my end. @camilogarciabotero is correct about the rounded edges being a deliberate expression of differentiation. The beloved and often overlooked heptagon is the same idea of R-ecosystem differentiation, but much more aggressive to the point of playful satire. I'm SO pleased @zzhaozheUM loves that best 💕.

@kdpsingh I can make whatever edits and send you the final SVG, but I'd like to wait until you all reach a consensus first.

**Comment by kdpsingh** [comment]
Awesome. I'll wait to hear from @rdboyes and then will make an executive decision.

**Comment by rdboyes** [comment]
I like number 2!

**Comment by kdpsingh** [comment]
Thanks! My amazing wife (who knows nothing about R and tidyverse) also votes for 2. Let's go with 2. Let's keep the rounded look per @camilogarciabotero suggestion. If you send me the vector graphic, I'll add it to the repo. Will keep the old graphic in the assets folder as a keepsake.

**Comment by pdimens** [comment]
Submitted PR. Did a few touchups to get nicer shadowing on the pliers and broom, converting the text to paths in the SVG so it always renders on any machine.
