### ISSUE TITLE
Supporting `contains` within `@filter`

### ISSUE THREAD

**Issue by joshualeond** [kdpsingh/Tidier.jl#62]
Hi there, thanks for this great addition to the Julia data ecosystem. 

I'm having trouble doing something similar to the following R code with the `Tidier.jl` package:

```r
library(dplyr)

df <- data.frame(
  player = c('P Guard', 'S Guard', 'S Forward', 'P Forward', 'Center'),
  points = c(12, 15, 19, 22, 32),
  rebounds = c(5, 7, 7, 12, 11)
)
df %>% filter(!grepl('Guard', player))
```

Which would filter out any records that have the word "Guard" in the `player` column. I am doing the following in Julia which results in an error:

```julia
using DataFrames, Tidier

df = DataFrame(
  player = ["P Guard", "S Guard", "S Forward", "P Forward", "Center"], 
  points = [12, 15, 19, 22, 32], 
  rebounds = [5, 7, 7, 12, 11]
)

@chain df begin
  @filter(!contains(player, "Guard"))
end
```

Here is the error:
> ERROR: MethodError: no method matching contains(::Vector{String}, ::String)

I'm not sure if this isn't supported by `Tidier.jl` yet or if I'm just approaching this the wrong way. This does work if I vectorize the `contains` method like so:

```julia
@chain df begin
  @filter(!contains.(player, "Guard"))
end
```
But I thought that `Tidier.jl` was doing the vectorizing under the hood.

**Comment by kdpsingh** [comment]
Thanks for bringing this up!

The reason `contains()` is not being vectorized is that `contains()` is on the do-not-vectorize list (see line 295 here: https://github.com/kdpsingh/Tidier.jl/blob/main/src/parsing.jl).

The main reason for this is that `contains()` is commonly used within selection helpers (e.g., `@select(contains("hello"))`, where it is typically not vectorized.

However, I just checked, and it seems like vectorizing it does not cause any problems in the selection context.

This is an easy fix -- will handle this in the next update this week. I'll also check to make sure that other selection helpers (e.g., `startswith()` [from base Julia], `starts_with()` [from Tidier]) similarly work fine when vectorized.

**Comment by joshualeond** [comment]
Thanks Karandeep! Thanks again for your effort with this package.
