### ISSUE TITLE
Implement `janitor::clean_names()`

### ISSUE THREAD

**Issue by kdpsingh** [kdpsingh/Tidier.jl#64]
This would be nice functionality to have. In R, this function cleans up column names in data frames, replacing spaces with underscores as well as a few other things.

Per https://cran.r-project.org/web/packages/janitor/vignettes/janitor.html#clean-dataframe-names-with-clean_names, here's what this function does:

- Parses letter cases and separators to a consistent format.
- Default is to snake_case, but other cases like camelCase are available
- Handles special characters and spaces, including transliterating characters like œ to oe.
- Appends numbers to duplicated names
- Converts “%” to “percent” and “#” to “number” to retain meaning
- Spacing (or lack thereof) around numbers is preserved

**Comment by werkstattcodes** [comment]
fyi - Maybe not new, there is a julia package with basically the same intention. Could be helpful.

https://github.com/TheRoniOne/Cleaner.jl

**Comment by kdpsingh** [comment]
Ooh I wasn't aware! Thank you for sharing. Let me review and see if there's any value to wrapping or re-exporting this.

**Comment by kdpsingh** [comment]
Actually, this package looks like it does the job. I don't think there's a need for us to build this out. I'm going to add a Resources section in our documentation to point to other packages that people coming from R may find helpful. I'll add this one there and then will close the issue.

**Comment by kdpsingh** [comment]
Resolved by #68. Implemented the `@clean_names` macro that wraps Cleaner.jl’s `polish_names()` function. Unlike `polish_names()`, the `@clean_names()` macro expects the optional `case` argument to be a string rather than a symbol, always returns a data frame, and can handle grouped data frames, in which the result is a grouped data frame.
